apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: route-kustomize-controller
  namespace: {{ .Release.Namespace }}
spec:
  description: "Describes the functionality of kustomize-controller"
  endpointSelector:
    matchLabels:
      io.cilium.k8s.policy.serviceaccount: kustomize-controller
  egress:
    - toEntities:
      - kube-apiserver

