apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: route-flux-check
  namespace: {{ .Release.Namespace }}
spec:
  description: "Describes the functionality of flux-check"
  endpointSelector:
    matchLabels:
      io.cilium.k8s.policy.serviceaccount: fluxcd-community-flux-check
  egress:
    - toEntities:
      - kube-apiserver

