apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: route-helm-controller
  namespace: {{ .Release.Namespace }}
spec:
  description: "Describes the functionality of helm-controller"
  endpointSelector:
    matchLabels:
      io.cilium.k8s.policy.serviceaccount: helm-controller
  egress:
    - toEntities:
      - kube-apiserver

