{{- if .Values.networkPolicy.enabled }}
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-good-client-full-egress
  namespace: {{ .Release.Namespace }}
spec:
  description: "Allow good-client full egress access"
  endpointSelector:
    matchLabels:
      io.cilium.k8s.policy.serviceaccount: good-client
  egress:
  - {}
  - toEntities:
    - "all"
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-server-full-egress
  namespace: {{ .Release.Namespace }}
spec:
  description: "Allow server full ingress access"
  endpointSelector:
    matchLabels:
      io.cilium.k8s.policy.serviceaccount: server
  ingress:
  - {}
  - fromEntities:
    - "all"
{{- end }}
