apiVersion: v1
kind: ServiceAccount
metadata:
  name: client
  namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: server
  namespace: {{ .Release.Namespace }}
