name: Root Specs
run-name: "Root Tests: ${{github.event_name}} on ${{github.ref_name}}#${{github.run_attempt}}"

on:
  workflow_call:

permissions:
  # Needed by junit-report
  checks: write
  # Needed by EncricoMi
  pull-requests: write

jobs:
  run-specs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Install Devbox
        uses: jetify-com/devbox-install-action@8c6a66ed6273138b1915457069de78cb52fe3bd7 # v0.15.0
        with:
          enable-cache: 'true'
          devbox-version: "0.17.2"

      - name: Run Unit Tests
        run: devbox run test -- --random examples --output junit

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@d0a4676d0e0b938bc201470d88276b7c74c712b3 # v2.24.0
        if: always()
        with:
          check_run: false
          files: |
            report/*.xml
