name: Root Specs
run-name: "Root Tests: ${{github.event_name}} on ${{github.ref_name}}#${{github.run_attempt}}"

on:
  workflow_call:

permissions:
  # Needed by junit-report
  checks: write
  # Needed by EncricoMi
  pull-requests: write

jobs:
  run-specs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install Devbox
        uses: jetify-com/devbox-install-action@8c6a66ed6273138b1915457069de78cb52fe3bd7 # v0.15.0
        with:
          enable-cache: 'true'
          devbox-version: "0.17.0"

      - name: Run Unit Tests
        run: devbox run test -- --random examples --output junit

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@c950f6fb443cb5af20a377fd0dfaa78838901040 # v2.23.0
        if: always()
        with:
          check_run: false
          files: |
            report/*.xml
