name: Terraform Workflow

on:
  workflow_call:
    inputs:
      apply_terraform:
        description: "Apply changes?"
        type: boolean
        required: true
      run_terraform:
        description: "Run terraform plan/apply?"
        type: boolean
        required: true
      run_specs:
        description: "Run spec tests?"
        type: boolean
        required: true
      terraform_project:
        description: "The project name (ie: github, talos, k8s, etc)"
        type: string
        required: true
      environment_name:
        description: "The environment to use"
        type: string
        required: true

jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: "${{ inputs.environment_name }}-${{ inputs.terraform_project }}"

    env:
      ##
      ## Secrets are tricky.  We want to expose _specific_ secrets to terraform
      ##   but these secrets vary from project to project.
      ##
      ## We could store all the secrets as terraform.tfvars, but then this makes
      ##   decrypting and using these secrets for local development a bit more
      ##   cumbersome.
      ##
      ## For the moment, we'll just include all the secrets for all our projects
      ##   and wait for this to become an unmaintainble mess
      ##

      ##
      ## Required For All
      ##
      AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
      AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
      TERRAFORM_TFPLAN: "${{ github.workspace }}/terraform.tfplan"
      TF_VAR_cloudflare_account_id: "${{ secrets.TF_VAR_cloudflare_account_id }}"
      TF_VAR_terraform_statefile_bucket: "${{ secrets.TF_VAR_terraform_statefile_bucket }}"
      TF_VAR_terraform_statefile_passphrase: "${{ secrets.TF_VAR_terraform_statefile_passphrase }}"

      ##
      ## GitHub Project
      ##
      SOPS_AGE_KEY: "${{ secrets.SOPS_AGE_KEY }}"
      TF_VAR_github_owner_slug: "${{ github.repository_owner }}"
      # specs
      SPEC_QUOTE: "${{ secrets.SPEC_QUOTE }}"

      ##
      ## Talos Project
      ##
      TF_VAR_cluster_name: "${{ secrets.TF_VAR_cluster_name }}"
      TF_VAR_cluster: "${{ secrets.TF_VAR_cluster }}"
      TF_VAR_nodes: "${{ secrets.TF_VAR_nodes }}"
      TF_VAR_talos_version: "${{ secrets.TF_VAR_talos_version }}"
      # Talos Spec
      TALOSCONFIG_TEXT: "${{ secrets.TALOSCONFIG_TEXT }}"
      # AWS_ACCESS_KEY_ID
      # AWS_SECRET_ACCESS_KEY
      # TF_VAR_cloudflare_account_id
      # TF_VAR_terraform_statefile_bucket

      ##
      ## K8s Project
      ##
      KUBECONFIG_TEXT: "${{ secrets.KUBECONFIG_TEXT }}"
      # TF_VAR_cluster <shared>
      # TF_VAR_nodes <shared>
      TF_VAR_flux_age: "${{ secrets.TF_VAR_flux_age }}"
      TF_VAR_flux_known_hosts: "${{ secrets.TF_VAR_flux_known_hosts }}"
      TF_VAR_flux_private_key: "${{ secrets.TF_VAR_flux_private_key }}"
      TF_VAR_flux_sync: "${{ secrets.TF_VAR_flux_sync }}"
      TF_VAR_root_domain: "${{ secrets.TF_VAR_root_domain }}"

    steps:
      - name: Generate Token
        # Used to provide feedback
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        id: app-token
        with:
          app-id: "${{ secrets.BOT_APP_ID }}"
          private-key: "${{ secrets.BOT_APP_PRIVATE_KEY }}"

      - name: Checkout
        id: checkout
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        #with:
        #  token: "${{ steps.elevated-app-token.outputs.token }}"

      - name: Install Devbox
        uses: jetify-com/devbox-install-action@8c6a66ed6273138b1915457069de78cb52fe3bd7 # v0.15.0
        with:
          enable-cache: 'true'
          devbox-version: "0.17.2"
          project-path: ".github/"

      - name: Create Wrapper
        uses: ./.github/actions/capture-wrapper
        with:
          command: "devbox"
          wrapper: "devbox-w"

      - name: Syntax Formatting
        id: fmt
        if: inputs.run_terraform
        run: devbox-w -c ".github/devbox.json" run "${{ inputs.terraform_project }}-tf" -- fmt -recursive -check .
        continue-on-error: true

      - name: Initialize
        id: init
        if: inputs.run_terraform
        run: devbox-w -c ".github/devbox.json" run "${{ inputs.terraform_project }}-tf" -- init -input=false

      - name: Validate
        id: validate
        if: steps.init.outcome == 'success'
        run: devbox-w -c ".github/devbox.json" run "${{ inputs.terraform_project }}-tf" -- validate

      - name: Plan
        id: plan
        if: steps.validate.outcome == 'success'
        run: devbox-w -c ".github/devbox.json" run "${{ inputs.terraform_project }}-tf" -- plan -input=false "-out=${TERRAFORM_TFPLAN}"
        env:
          GITHUB_TOKEN: "${{ steps.app-token.outputs.token }}"
        continue-on-error: true

      - name: Find PR
        uses: jwalton/gh-find-current-pr@f3d61b485d2801773f7a07b2aaa3306bd8f8e653 # v1
        id: findPR
        with:
          # Can be "open", "closed", or "all".  Defaults to "open".
          state: open

      - name: Plan Markdown
        if: steps.plan.outcome == 'success' && steps.findPR.outputs.number
        id: plan-md
        shell: bash
        run: |
          set -exuo pipefail

          CAPTURE=$(mktemp -u)
          devbox -c ".github/devbox.json" run "${{ inputs.terraform_project }}-tf" -- show "-plan=${TERRAFORM_TFPLAN}" -no-color > "${CAPTURE}"
          # There is a change our tfplan contains no work, therefore we'll
          #   zero-out our counters
          tf_add=0
          tf_change=0
          tf_destroy=0
          set +e
          read tf_add tf_change tf_destroy < <(sed -nE 's/^Plan: +([0-9]+) +to add, +([0-9]+) +to change, +([0-9]+) +to destroy.*/\1 \2 \3/p' "${CAPTURE}")
          set -e

          # Try to classify a color-code based on the outcome
          if (( tf_add != 0 || tf_change != 0 )); then
            emoji="🟨"
          elif (( tf_destroy != 0 )); then
            emoji="🟥"
          else
            emoji="🟩"
          fi

          ## Process CAPTURE using `diff` highlighting
          ##  Github diff highlighting only supports
          ##  `+ add in green`
          ##  `- delete in red`
          ##  `! change in yellow`
          ##  `# comment in gray`

          ##
          ## Process add/remove resources...
          ##
          # # github_actions_secret.encrypted_shared_secrets["shared#TF_VAR_terraform_statefile_bucket"] must be replaced
          #-/+ resource "github_actions_secret" "encrypted_shared_secrets" {
          #  ~ created_at       = "2025-11-12 19:50:20 +0000 UTC" -> (known after apply)
          #  ~ encrypted_value  = (sensitive value) # forces replacement
          #  ~ id               = "k6haze:TF_VAR_terraform_statefile_bucket" -> (known after apply)
          #  ~ updated_at       = "2025-11-12 19:50:20 +0000 UTC" -> (known after apply)
          #    # (3 unchanged attributes hidden)
          #}
          #
          sed -i '/# forces replacement/ s/^ /-/' "${CAPTURE}"
          sed -i '/^[[:space:]]*~/ s/^ /!/' "${CAPTURE}"
          sed -i '/^-\/\+/ s/^/!/' "${CAPTURE}"

          # Highlight comments
          sed -i '/^[[:space:]]*#/ s/^ /#/' "${CAPTURE}"

          ##
          ## Destroy resources
          ##
          sed -i '/^[[:space:]]*-/ s/^ /-/' "${CAPTURE}"

          ##
          ## Add resources
          ##
          ## NOTE:  This line is a bit flacky and it'll match everything that
          ##  does not contain a starting character.  hence, we add it as our last line
          #  # github_actions_environment_secret.encrypted_secrets["curator#BOT_APP_ID"] will be created
          #  + resource "github_actions_environment_secret" "encrypted_secrets" {
          #      + created_at      = (known after apply)
          #      + encrypted_value = (sensitive value)
          #      + environment     = "curator"
          #      + id              = (known after apply)
          #      + repository      = "k6haze"
          #      + secret_name     = "BOT_APP_ID"
          #      + updated_at      = (known after apply)
          #    }
          sed -i '/^[[:space:]]*\+/ s/^ /\+/' "${CAPTURE}"

          {
            echo "markdown<<${CAPTURE}"
            echo "#### Outcome: $emoji  add=$tf_add change=$tf_change destroy=$tf_destroy"
            cat <<'EOL'
          #### Terraform Format and Style 🖌`${{ steps.fmt.outcome }}`
          #### Terraform Initialization ⚙️`${{ steps.init.outcome }}`
          #### Terraform Validation 🤖`${{ steps.validate.outcome }}`
          <details><summary>Validation Output</summary>

          ```\n
          ${{ steps.validate.outputs.stdout }}
          ```

          </details>

          #### Terraform Plan 📖`${{ steps.plan.outcome }}`

          <details><summary>Show Plan</summary>

          ```diff
          EOL
            cat "${CAPTURE}"
            cat <<'EOL'
          ```

          </details>

          *Pusher: @${{ github.actor }}, Action: `${{ github.event_name }}`, Working Directory: `${{ env.tf_actions_working_dir }}`, Workflow: `${{ github.workflow }}`*`;
          EOL
            echo "${CAPTURE}" # Our ending marker
          } >> "$GITHUB_OUTPUT"

          rm "${CAPTURE}"


      - name: "Update PR ${{ steps.findPR.outputs.number }}"
        id: plan-pr
        if: steps.plan-md.outcome == 'success' && steps.findPR.outputs.number
        uses: marocchino/sticky-pull-request-comment@70d2764d1a7d5d9560b100cbea0077fc8f633987 # v3
        with:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
          number: ${{ steps.findPR.outputs.number }}
          header: "${{ inputs.environment_name }}-${{ inputs.terraform_project }}"
          message: ${{ steps.plan-md.outputs.markdown }}
#          message: |
#            ```
#            hello world
#            ```

      - name: "Check Plan Results"
        id: plan-check
        if: steps.plan.outcome != 'skipped'
        # Terminate the pipeline if the plan had failed
        run: "exit ${{ steps.plan.outputs.exit-code }}"

      - name: Apply
        id: apply
        if: steps.plan-check.outcome == 'success' && inputs.apply_terraform
        run: devbox -c ".github/devbox.json" run "${{ inputs.terraform_project }}-tf" -- apply -input=false "${TERRAFORM_TFPLAN}"
        env:
          GITHUB_TOKEN: "${{ steps.app-token.outputs.token }}"

      - name: Run Specs
        id: spec-test
        if: inputs.run_specs && (steps.apply.outcome == 'success' || steps.apply.outcome == 'skipped')
        run: devbox-w -c ".github/devbox.json" run "${{ inputs.terraform_project }}-spec" -- --random examples --output junit
        continue-on-error: true

      - name: Publish Spec Results
        uses: EnricoMi/publish-unit-test-result-action@c950f6fb443cb5af20a377fd0dfaa78838901040 # v2.23.0
        if: always() && steps.spec-test.outcome != 'skipped'
        with:
          check_run: false
          files: |
            report/*.xml

      - name: Check Spec Results
        id: spec-check
        if: steps.spec-test.outcome != 'skipped'
        run: "exit ${{ steps.spec-test.outputs.exit-code }}"
