name: Terraform Deploy
run-name: "Deploy Github ${{github.ref_name}} #${{github.run_attempt}}"

on:
  push:
    branches: ["main"]
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - '**'
#    paths:
#      - terraform/github/**

permissions:
  actions: write
  contents: write
  issues: write
  pull-requests: write
  statuses: read
  #contents: read
  #environments: write
  #secrets: write
  #variables: write
 
jobs:
  is-latest-checkout:
    name: "Check if current commit is latest"
    # We want to avoid running terraform plan/apply on stale commits
    #   this avoid accidently re-running an old GHA.
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Check branch-head equals current checkout
        id: run-version-check
        env:
          BRANCH_NAME: ${{ github.ref }}
          GITHUB_SHA: ${{ github.sha }}
        shell: bash
        run: |
          set -euo pipefail

          ORIGIN_SHA=$(git ls-remote origin "${BRANCH_NAME}" | awk '{print $1}')
          echo "current sha: ${GITHUB_SHA}"
          echo "origin sha: ${ORIGIN_SHA}"

          if [[ "${GITHUB_SHA}" != "${ORIGIN_SHA}" ]]; then
            echo "current sha(${GITHUB_SHA}) is NOT the latest origin sha(${ORIGIN_SHA}) -- pipeline aborted."
            exit 10
          fi

  determine-changes:
    name: "Determine what changed"
    runs-on: ubuntu-latest
    outputs:
      changes: ${{ steps.determine.outputs.changes }}
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            git diff --name-only origin/${{ github.base_ref }}...HEAD
          else
            git diff --name-only HEAD~1 HEAD
          fi | tee changed_files.txt

      - name: Determine changes
        id: determine
        env:
          VERBOSE: "yes"
        run: |
          RESULT=$(cat changed_files.txt | .github/scripts/determine.sh)
          echo "changes=$RESULT" >> $GITHUB_OUTPUT

  ##
  ## Root Specs
  ##
  run-root-spec:
    uses: ./.github/workflows/ci-pipeline.yaml
    needs: [determine-changes, is-latest-checkout]
    if: fromJSON(needs.determine-changes.outputs.changes).changed_root_spec == true

  ##
  ## GitHub
  ##
  deploy-github:
    uses: ./.github/workflows/deploy-terraform.yaml
    needs: [determine-changes, is-latest-checkout]
    if: |
      fromJSON(needs.determine-changes.outputs.changes).changed_github == true ||
      fromJSON(needs.determine-changes.outputs.changes).changed_github_spec == true
    with:
      apply_terraform: "true" # secrets will always be applied, as they'll be needed further in our pipeline
      run_terraform: ${{ fromJSON(needs.determine-changes.outputs.changes).changed_github }}
      run_specs: ${{ fromJSON(needs.determine-changes.outputs.changes).changed_github_spec }}
      environment_name: curator
      terraform_project: "github"
    secrets: inherit # share secrets with the reusable workflow

  ##
  ## Talos
  ##
  deploy-talos:
    uses: ./.github/workflows/deploy-terraform.yaml
    needs: [determine-changes, deploy-github]
    # run this unless deploy-github failed or was cancelled
    if: |
      always() && (needs.deploy-github.result == 'success' || needs.deploy-github.result == 'skipped') &&
      (fromJSON(needs.determine-changes.outputs.changes).changed_talos == true ||
       fromJSON(needs.determine-changes.outputs.changes).changed_talos_spec == true)
    with:
      apply_terraform: ${{ github.ref == 'refs/heads/main' }}
      run_terraform: ${{ fromJSON(needs.determine-changes.outputs.changes).changed_talos }}
      run_specs: ${{ fromJSON(needs.determine-changes.outputs.changes).changed_talos_spec }}
      environment_name: development
      terraform_project: "talos"
    secrets: inherit # share secrets with the reusable workflow

  ##
  ## Kubernetes
  ##
  deploy-k8s:
    uses: ./.github/workflows/deploy-terraform.yaml
    needs: [determine-changes, deploy-talos]
    # run this unless deploy-talos failed or was cancelled
    if: |
      always() && (needs.deploy-talos.result == 'success' || needs.deploy-talos.result == 'skipped') &&
      (fromJSON(needs.determine-changes.outputs.changes).changed_k8s == true ||
       fromJSON(needs.determine-changes.outputs.changes).changed_k8s_spec == true)
    with:
      apply_terraform: ${{ github.ref == 'refs/heads/main' }}
      run_terraform: ${{ fromJSON(needs.determine-changes.outputs.changes).changed_k8s }}
      run_specs: ${{ fromJSON(needs.determine-changes.outputs.changes).changed_k8s_spec }}
      environment_name: development
      terraform_project: "k8s"
    secrets: inherit # share secrets with the reusable workflow
