name: 🔍 Testing
run-name: "Manual Testing ${{github.ref_name}} #${{github.run_attempt}}"

on:
  workflow_dispatch:
    inputs:
      stack_name:
        description: "The testing configuration and component to run"
        type: choice
        required: true
        default: "development-talos"
        options:
          - curator-github
          - development-talos
          - production-talos

permissions:
  actions: write
  contents: write
  issues: write
  pull-requests: write
  statuses: read
  #contents: read
  #environments: write
  #secrets: write
  #variables: write

jobs:
  args:
    name: "Parse Arguments"
    runs-on: ubuntu-latest

    outputs:
      project_name: ${{ steps.split.outputs.project_name }}
      environment_name: ${{ steps.split.outputs.environment_name }}
    steps:
      - name: Split
        id: split
        shell: bash
        run: |
          STACK_NAME="${{ inputs.stack_name }}"
          echo "project_name=${STACK_NAME##*-}" >> "${GITHUB_OUTPUT}"
          echo "environment_name=${STACK_NAME%-*}" >> "${GITHUB_OUTPUT}"


  test:
    uses: ./.github/workflows/_terraform-workflow.yaml
    needs:
      - args
    with:
      environment_name: ${{ needs.args.outputs.environment_name }}
      terraform_project: ${{ needs.args.outputs.project_name }}
      apply_terraform: false
      run_terraform: false
      run_specs: true
    secrets: inherit # share secrets with the reusable workflow
