name: 🛠️ Terraform
run-name: "Manual Terraform: ${{github.event_name}} on ${{github.ref_name}}#${{github.run_attempt}}"

on:
  workflow_dispatch:
    inputs:
      stack_name:
        description: "The terraform configuration to run"
        type: choice
        required: true
        default: "development-talos"
        options:
          - curator-github
          - development-talos
          - production-talos
      apply_terraform:
        description: "Apply changes?"
        type: boolean
        required: false
        default: false

permissions:
  actions: write
  contents: write
  issues: write
  pull-requests: write
  statuses: read
  #contents: read
  #environments: write
  #secrets: write
  #variables: write

jobs:
  is-latest-checkout:
    name: "Check if current commit is latest"
    # We want to avoid running terraform plan/apply on stale commits
    #   this avoid accidently re-running an old GHA.
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Check branch-head equals current checkout
        id: run-version-check
        env:
          BRANCH_NAME: ${{ github.ref }}
          GITHUB_SHA: ${{ github.sha }}
        shell: bash
        run: |
          set -euo pipefail

          ORIGIN_SHA=$(git ls-remote origin "${BRANCH_NAME}" | awk '{print $1}')
          echo "current sha: ${GITHUB_SHA}"
          echo "origin sha: ${ORIGIN_SHA}"

          if [[ "${GITHUB_SHA}" != "${ORIGIN_SHA}" ]]; then
            echo "current sha(${GITHUB_SHA}) is NOT the latest origin sha(${ORIGIN_SHA}) -- pipeline aborted."
            exit 10
          fi
  args:
    name: "Parse Arguments"
    runs-on: ubuntu-latest

    outputs:
      project_name: ${{ steps.split.outputs.project_name }}
      environment_name: ${{ steps.split.outputs.environment_name }}
    steps:
      - name: Split
        id: split
        shell: bash
        run: |
          STACK_NAME="${{ inputs.stack_name }}"
          echo "project_name=${STACK_NAME##*-}" >> "${GITHUB_OUTPUT}"
          echo "environment_name=${STACK_NAME%-*}" >> "${GITHUB_OUTPUT}"


  deploy:
    uses: ./.github/workflows/deploy-terraform.yaml
    needs:
      - is-latest-checkout
      - args
    with:
      environment_name: ${{ needs.args.outputs.environment_name }}
      apply_terraform: ${{ inputs.apply_terraform }}
      terraform_project: ${{ needs.args.outputs.project_name }}
    secrets: inherit # share secrets with the reusable workflow
